
#
# ...-alpine3.17 segfault with no data at StdErr.txt
# ...-alpine3.16 -- Ok
# https://github.com/dotnet/runtime/issues/81218
#

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine3.16 as builder

RUN apk add --no-cache python3 py3-pip

COPY src ./src
COPY restler ./restler
COPY build-restler.py .

RUN python3 build-restler.py --dest_dir /build

RUN python3 -m compileall -b /build/engine

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.16 as target

RUN apk add --no-cache python3 py3-pip
RUN pip3 install requests applicationinsights

COPY --from=builder /build /RESTler
