#!/usr/bin/env bash

IN_FILE="${1:-/wrk/oapispec}"
OUT_FILE="${2:-/wrk/oapispec}"

docker-entrypoint.sh \
  generate \
  --skip-validate-spec \
  --generator-name openapi \
  --log-to-stderr \
  --input-spec "$IN_FILE" \
  --output /tmp/oapiconv \
&& mv -v /tmp/oapiconv/openapi.json "$OUT_FILE"

